# XGBoost Classifier: Predict the Percent Chance of Rain Happening

In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xgboost
from imblearn.combine import SMOTEENN
from scipy.constants import precision
import optuna
import optuna.visualization as vis
import plotly  

from sklearn.metrics import r2_score, accuracy_score, confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeRegressor
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler


from joblib import dump, load

In [108]:
data_frame = pd.read_csv('weather_data_excel.csv')

In [109]:
data_frame['Date'] = pd.to_datetime(data_frame['Date'])

In [110]:
data_frame['Month'] = data_frame['Date'].dt.month
data_frame['Day'] = data_frame['Date'].dt.day

In [111]:
# This is the threshold, in mm, for if rainfall is classified as rain or not
# 0.254mm is the threshold the National Weather Service uses when determine if precipitation should be reported as rain
threshold = 0.254
data_frame['Rainfall'] = (data_frame['Precipitation_mm'] >= threshold).astype(int)

In [112]:
data_frame_pos = data_frame[data_frame['Rainfall']==1]
data_frame_neg = data_frame[data_frame['Rainfall']==0]

num = data_frame.shape[0]
num_pos = data_frame_pos.shape[0]
num_neg = data_frame_neg.shape[0]

print('Number of examples = ', num)
print('Number of positive examples = ', num_pos)
print('Number of negative examples = ', num_neg)
print(f'Percentage of positive examples = {np.round((num_pos / num) * 100, 4)}%')

Number of examples =  1000000
Number of positive examples =  975735
Number of negative examples =  24265
Percentage of positive examples = 97.5735%

In [113]:
data_frame.sample(5)

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh,Temperature_F,Date,Military_Time,Rain_Category,Rain_Cat_Num,Precipitation_in,Lat,Long,Month,Day,Rainfall
302800,Philadelphia,4/4/2024 1:45,14.674227,69.053557,3.117412,12.503579,58.413608,2024-04-04,01:45,Moderate Rain,1,0.122733,39.9526,75.1652,4,4,1
587086,Phoenix,4/13/2024 0:54,5.690946,59.936744,5.981417,27.108093,42.243703,2024-04-13,00:54,Moderate Rain,1,0.235489,33.4484,112.0740,4,13,1
662684,San Diego,1/9/2024 15:35,10.674694,30.931704,6.740942,20.485032,51.214449,2024-01-09,15:35,Moderate Rain,1,0.265391,32.7157,117.1611,1,9,1
694523,San Diego,2/14/2024 20:17,-1.612218,73.295140,7.061364,2.361418,29.098008,2024-02-14,20:17,Moderate Rain,1,0.278006,32.7157,117.1611,2,14,1
988776,Phoenix,3/11/2024 17:37,7.740572,78.819720,9.996889,16.017974,45.933030,2024-03-11,17:37,Heavy Rain,2,0.393578,33.4484,112.0740,3,11,1

In [114]:
y=data_frame['Rainfall']

In [115]:
X = data_frame.drop(columns=['Precipitation_in', 'Precipitation_mm', 'Date', 'Military_Time', 'Rain_Category', 'Rain_Cat_Num', 'Location', 'Rainfall', 'Date_Time', 'Temperature_C', 'Location'])

In [116]:
X.columns

Index(['Humidity_pct', 'Wind_Speed_kmh', 'Temperature_F', 'Lat', 'Long',
       'Month', 'Day'],
      dtype='object')

In [117]:
X.sample(5)

,Humidity_pct,Wind_Speed_kmh,Temperature_F,Lat,Long,Month,Day
186739,54.634551,20.670871,99.150426,32.7767,96.7970,4,25
639678,46.868478,25.250259,32.425423,29.7601,95.3701,1,5
834759,41.595965,8.805635,99.887366,29.7601,95.3701,5,9
315247,55.806553,23.805502,76.484979,37.3387,121.8853,3,8
11793,75.038771,11.550053,82.391121,40.7128,74.0060,4,1

In [118]:
y.sample(5)

821451    1
124483    1
488307    1
148901    1
399874    1
Name: Rainfall, dtype: int64

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 4700)

In [120]:
scaler = StandardScaler()
X_scaler = scaler.fit_transform(X_train)

In [121]:
# Combine both Over and Under Sampling
smote_enn = SMOTEENN(random_state=4700)
X_resampled, y_resampled = smote_enn.fit_resample(X_scaler, y_train)

## Create UnTuned XGBoost Model

In [122]:
xgb_c = xgboost.XGBClassifier( random_state = 4700)

In [123]:
xgb_c.fit(X_resampled, y_resampled)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=4700, ...)

In [124]:
y_train_pred = xgb_c.predict(X_resampled)

train_precision_score =   precision_score(y_resampled, y_train_pred)
train_recall_score = recall_score(y_resampled, y_train_pred)
train_f1_score = f1_score(y_resampled, y_train_pred)

print('Training Scores')
print('Precision Score:', train_precision_score)
print('Recall Score:', train_recall_score)
print('F1 Score:', train_f1_score)

Training Scores
Precision Score: 0.8195848619449817
Recall Score: 0.9995428633320644
F1 Score: 0.9006626508617905

In [125]:
y_test_pred = xgb_c.predict(X_test)

test_precision_score =   precision_score(y_test, y_test_pred)
test_recall_score = recall_score(y_test, y_test_pred)
test_f1_score = f1_score(y_test, y_test_pred)

print('Testing Scores')
print('Precision Score:', test_precision_score)
print('Recall Score:', test_recall_score)
print('F1 Score:', test_f1_score)

Testing Scores
Precision Score: 0.9759340106002481
Recall Score: 0.963193892973333
F1 Score: 0.9695221003450036

In [126]:
y_resampled.sample(20)

398534     0
1299682    1
483295     0
426884     0
981021     1
577165     0
311969     0
501293     0
1164793    1
917210     1
340817     0
1325695    1
682879     0
936404     1
1339134    1
1384815    1
1229946    1
594111     0
437403     0
645858     0
Name: Rainfall, dtype: int64

## Implement Optuna Hyper Parameter Tuning

In [127]:
def objective(trial):
    # Define hyperparameters to optimize
    objective = 'binary:logistic'
    max_depth = trial.suggest_int('max_depth', 1, 60)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 1)
    reg_lambda = trial.suggest_float('reg_lambda', 0.00, 10.0)

    params = {
        'objective': objective,
        'max_depth': max_depth,
        'learning_rate': learning_rate,
        'eval_metric': 'logloss',
        'tree_method': 'approx',
        "reg_lambda": reg_lambda,
    }

    
    X_train, X_val, y_train, y_val = train_test_split(X_resampled, y_resampled, test_size=0.2)
    
    
    dtrain = xgboost.DMatrix(X_train, label=y_train)
    dval = xgboost.DMatrix(X_val, label=y_val)
    
    
    evals = [(dtrain, 'train'), (dval, 'validation')]

    
    model = xgboost.train(params, 
                          dtrain, 
                          num_boost_round=100, 
                          evals=evals, 
                          early_stopping_rounds=10, 
                          verbose_eval=False)

    
    predictions_val = model.predict(dval)
    predictions_binary_val = [1 if p > 0.5 else 0 for p in predictions_val]

    
    f1 = f1_score(y_val, predictions_binary_val)

    return f1

In [128]:
study = optuna.create_study(direction='maximize')

[I 2024-10-31 14:28:48,918] A new study created in memory with name: no-name-07378d03-8c80-42a0-88df-a4d254ae7529

In [129]:
len(X_resampled)

1385501

In [130]:
len(y_resampled)

1385501

In [131]:
study.optimize(objective, n_trials=50, n_jobs=-1)

[I 2024-10-31 14:30:19,079] Trial 30 finished with value: 0.5739828664548492 and parameters: {'max_depth': 2, 'learning_rate': 0.037398347844587905, 'reg_lambda': 3.1873298658951352}. Best is trial 30 with value: 0.5739828664548492.
[I 2024-10-31 14:30:53,237] Trial 29 finished with value: 0.936289290764753 and parameters: {'max_depth': 4, 'learning_rate': 0.43667725278974295, 'reg_lambda': 4.6705979668505515}. Best is trial 29 with value: 0.936289290764753.
[I 2024-10-31 14:31:48,828] Trial 27 finished with value: 0.9492754731993941 and parameters: {'max_depth': 7, 'learning_rate': 0.9716750141455397, 'reg_lambda': 2.547157732108066}. Best is trial 27 with value: 0.9492754731993941.
[I 2024-10-31 14:32:41,639] Trial 28 finished with value: 0.9672136261542301 and parameters: {'max_depth': 9, 'learning_rate': 0.8768702106304671, 'reg_lambda': 2.210460212860359}. Best is trial 28 with value: 0.9672136261542301.
[I 2024-10-31 14:34:05,786] Trial 33 finished with value: 0.938484584723317 and parameters: {'max_depth': 8, 'learning_rate': 0.24792744149919738, 'reg_lambda': 9.66404717428636}. Best is trial 28 with value: 0.9672136261542301.
[I 2024-10-31 14:35:17,242] Trial 19 finished with value: 0.9833499820351952 and parameters: {'max_depth': 14, 'learning_rate': 0.8842751266315587, 'reg_lambda': 3.6233966980376984}. Best is trial 19 with value: 0.9833499820351952.
[I 2024-10-31 14:36:08,096] Trial 21 finished with value: 0.9837994488962087 and parameters: {'max_depth': 16, 'learning_rate': 0.9719817994213472, 'reg_lambda': 7.99063531455729}. Best is trial 21 with value: 0.9837994488962087.
[I 2024-10-31 14:36:17,174] Trial 36 finished with value: 0.936592756229896 and parameters: {'max_depth': 4, 'learning_rate': 0.5696988308870425, 'reg_lambda': 5.599372718064722}. Best is trial 21 with value: 0.9837994488962087.
[I 2024-10-31 14:36:51,464] Trial 4 finished with value: 0.9849343088663363 and parameters: {'max_depth': 16, 'learning_rate': 0.5322574952370898, 'reg_lambda': 1.4821288509305586}. Best is trial 4 with value: 0.9849343088663363.
[I 2024-10-31 14:37:15,688] Trial 18 finished with value: 0.9855985598559855 and parameters: {'max_depth': 25, 'learning_rate': 0.8299006338226411, 'reg_lambda': 4.4128610033421}. Best is trial 18 with value: 0.9855985598559855.
[I 2024-10-31 14:38:44,474] Trial 34 finished with value: 0.9848164232135808 and parameters: {'max_depth': 27, 'learning_rate': 0.9923164357892619, 'reg_lambda': 2.444277282774432}. Best is trial 18 with value: 0.9855985598559855.
[I 2024-10-31 14:39:34,681] Trial 14 finished with value: 0.9861505906133535 and parameters: {'max_depth': 37, 'learning_rate': 0.7237870536463382, 'reg_lambda': 3.5937417755659693}. Best is trial 14 with value: 0.9861505906133535.
[I 2024-10-31 14:39:41,633] Trial 35 finished with value: 0.98198226576158 and parameters: {'max_depth': 14, 'learning_rate': 0.5862145638788294, 'reg_lambda': 8.2154935298766}. Best is trial 14 with value: 0.9861505906133535.
[I 2024-10-31 14:40:20,773] Trial 25 finished with value: 0.9857046900312142 and parameters: {'max_depth': 28, 'learning_rate': 0.6350162872222272, 'reg_lambda': 4.81139589064281}. Best is trial 14 with value: 0.9861505906133535.
[I 2024-10-31 14:41:00,688] Trial 32 finished with value: 0.985786144649668 and parameters: {'max_depth': 51, 'learning_rate': 0.8549254030929566, 'reg_lambda': 2.37866034078434}. Best is trial 14 with value: 0.9861505906133535.
[I 2024-10-31 14:41:08,696] Trial 11 finished with value: 0.9858147930881074 and parameters: {'max_depth': 52, 'learning_rate': 0.5478148264901931, 'reg_lambda': 0.6308933132447525}. Best is trial 14 with value: 0.9861505906133535.
[I 2024-10-31 14:41:58,973] Trial 13 finished with value: 0.9861890239084746 and parameters: {'max_depth': 31, 'learning_rate': 0.6606462659447574, 'reg_lambda': 9.09040388478788}. Best is trial 13 with value: 0.9861890239084746.
[I 2024-10-31 14:42:38,779] Trial 5 finished with value: 0.9858233541794078 and parameters: {'max_depth': 56, 'learning_rate': 0.8799819158228228, 'reg_lambda': 3.9694090294407403}. Best is trial 13 with value: 0.9861890239084746.
[I 2024-10-31 14:43:47,263] Trial 31 finished with value: 0.9859781970616857 and parameters: {'max_depth': 37, 'learning_rate': 0.8646485603914961, 'reg_lambda': 9.756281862399671}. Best is trial 13 with value: 0.9861890239084746.
[I 2024-10-31 14:44:22,097] Trial 0 finished with value: 0.986372710702196 and parameters: {'max_depth': 43, 'learning_rate': 0.5108136365920442, 'reg_lambda': 3.006867379729441}. Best is trial 0 with value: 0.986372710702196.
[I 2024-10-31 14:45:04,990] Trial 16 finished with value: 0.9866243625703695 and parameters: {'max_depth': 60, 'learning_rate': 0.5677159808371905, 'reg_lambda': 1.495734101856171}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:47:36,827] Trial 23 finished with value: 0.9840083952009523 and parameters: {'max_depth': 26, 'learning_rate': 0.14928040896726003, 'reg_lambda': 6.68816123426177}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:47:46,833] Trial 1 finished with value: 0.986548325653813 and parameters: {'max_depth': 51, 'learning_rate': 0.39897425748926585, 'reg_lambda': 1.5349514814946597}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:48:32,413] Trial 41 finished with value: 0.984349021172066 and parameters: {'max_depth': 49, 'learning_rate': 0.7388699319441856, 'reg_lambda': 0.027379814048500428}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:49:10,253] Trial 43 finished with value: 0.9846979568249645 and parameters: {'max_depth': 51, 'learning_rate': 0.731170684124336, 'reg_lambda': 0.27311251708952344}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:49:29,649] Trial 39 finished with value: 0.9855103303424007 and parameters: {'max_depth': 23, 'learning_rate': 0.32617259091510237, 'reg_lambda': 6.643556589876712}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:49:36,268] Trial 37 finished with value: 0.9861941018682275 and parameters: {'max_depth': 38, 'learning_rate': 0.6943665885768987, 'reg_lambda': 5.36839835998653}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:50:04,752] Trial 42 finished with value: 0.9853125319934792 and parameters: {'max_depth': 50, 'learning_rate': 0.646654644849457, 'reg_lambda': 0.3136377435668001}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:50:09,061] Trial 15 finished with value: 0.9861455389424822 and parameters: {'max_depth': 58, 'learning_rate': 0.3439991301033671, 'reg_lambda': 0.27575525881933016}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:50:28,327] Trial 45 finished with value: 0.9854632720050754 and parameters: {'max_depth': 47, 'learning_rate': 0.7217342180358108, 'reg_lambda': 0.39906497242074845}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:50:30,101] Trial 46 finished with value: 0.9849770669361269 and parameters: {'max_depth': 52, 'learning_rate': 0.7052446579286011, 'reg_lambda': 0.18058024721471533}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:50:30,770] Trial 9 finished with value: 0.9865959989115903 and parameters: {'max_depth': 59, 'learning_rate': 0.4886341927319787, 'reg_lambda': 7.70953599114173}. Best is trial 16 with value: 0.9866243625703695.
[I 2024-10-31 14:50:46,079] Trial 7 finished with value: 0.986885361801407 and parameters: {'max_depth': 40, 'learning_rate': 0.2987865085611554, 'reg_lambda': 3.6014127143841868}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:50:50,640] Trial 47 finished with value: 0.9848001797023089 and parameters: {'max_depth': 47, 'learning_rate': 0.7082988867978464, 'reg_lambda': 0.015629841368398623}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:52:56,146] Trial 48 finished with value: 0.9862268495738944 and parameters: {'max_depth': 41, 'learning_rate': 0.7149611363937691, 'reg_lambda': 6.437023735206049}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:53:35,926] Trial 12 finished with value: 0.9864075368845174 and parameters: {'max_depth': 58, 'learning_rate': 0.3700654617620869, 'reg_lambda': 6.445296114260698}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:53:45,320] Trial 49 finished with value: 0.9858655433707546 and parameters: {'max_depth': 38, 'learning_rate': 0.6883569307685805, 'reg_lambda': 6.342285891281881}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:53:57,982] Trial 44 finished with value: 0.9859677138836624 and parameters: {'max_depth': 51, 'learning_rate': 0.7369830702779142, 'reg_lambda': 5.73837286890131}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:56:31,185] Trial 26 finished with value: 0.986858482305871 and parameters: {'max_depth': 46, 'learning_rate': 0.23781644124047469, 'reg_lambda': 2.2615369682105415}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:57:06,174] Trial 22 finished with value: 0.986637163960502 and parameters: {'max_depth': 40, 'learning_rate': 0.20397934633951106, 'reg_lambda': 6.165508704585825}. Best is trial 7 with value: 0.986885361801407.
[I 2024-10-31 14:57:26,033] Trial 10 finished with value: 0.9870048265542958 and parameters: {'max_depth': 57, 'learning_rate': 0.2611571626731839, 'reg_lambda': 4.838896332667466}. Best is trial 10 with value: 0.9870048265542958.
[I 2024-10-31 14:57:34,450] Trial 20 finished with value: 0.9872090601508191 and parameters: {'max_depth': 38, 'learning_rate': 0.17759220467737735, 'reg_lambda': 1.8231930773654492}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 14:58:45,166] Trial 3 finished with value: 0.9868411727184673 and parameters: {'max_depth': 56, 'learning_rate': 0.247098697727999, 'reg_lambda': 3.5811241408422334}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 14:59:48,222] Trial 24 finished with value: 0.986735451658266 and parameters: {'max_depth': 59, 'learning_rate': 0.2323023688340788, 'reg_lambda': 7.052687892732172}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 15:00:22,793] Trial 38 finished with value: 0.9865989583538679 and parameters: {'max_depth': 57, 'learning_rate': 0.27328286772169486, 'reg_lambda': 5.516322167114385}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 15:01:38,567] Trial 6 finished with value: 0.9804255186300985 and parameters: {'max_depth': 50, 'learning_rate': 0.05969144983503544, 'reg_lambda': 9.07561568118033}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 15:02:20,993] Trial 17 finished with value: 0.9868871936706022 and parameters: {'max_depth': 59, 'learning_rate': 0.17957387793325977, 'reg_lambda': 8.472870756500345}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 15:02:47,176] Trial 2 finished with value: 0.9806528208452773 and parameters: {'max_depth': 51, 'learning_rate': 0.0443720204554986, 'reg_lambda': 6.043310413710735}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 15:03:01,862] Trial 8 finished with value: 0.9867898718408635 and parameters: {'max_depth': 60, 'learning_rate': 0.12816716993211102, 'reg_lambda': 1.676444791182814}. Best is trial 20 with value: 0.9872090601508191.
[I 2024-10-31 15:03:25,819] Trial 40 finished with value: 0.9857037316482756 and parameters: {'max_depth': 46, 'learning_rate': 0.09531559199127285, 'reg_lambda': 3.0011819199280856}. Best is trial 20 with value: 0.9872090601508191.

In [132]:
study.best_params

{'max_depth': 38,
 'learning_rate': 0.17759220467737735,
 'reg_lambda': 1.8231930773654492}

In [133]:
!pip install optuna[visualization]

Requirement already satisfied: optuna[visualization] in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (4.0.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (1.13.3)
Requirement already satisfied: colorlog in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (6.8.2)
Requirement already satisfied: numpy in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (2.1.2)
Requirement already satisfied: packaging>=20.0 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (24.1)
Requirement already satisfied: sqlalchemy>=1.3.0 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (2.0.36)
Requirement already satisfied: tqdm in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (4.66.6)
Requirement already satisfied: PyYAML in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from optuna[visualization]) (6.0.2)
Requirement already satisfied: Mako in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from alembic>=1.5.0->optuna[visualization]) (1.3.6)
Requirement already satisfied: typing-extensions>=4 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from alembic>=1.5.0->optuna[visualization]) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from sqlalchemy>=1.3.0->optuna[visualization]) (3.1.1)
Requirement already satisfied: colorama in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from colorlog->optuna[visualization]) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from Mako->alembic>=1.5.0->optuna[visualization]) (2.1.5)

WARNING: optuna 4.0.0 does not provide the extra 'visualization'

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [134]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from plotly) (9.0.0)
Requirement already satisfied: packaging in c:\users\david\pycharmprojects\pythonproject\.venv\lib\site-packages (from plotly) (24.1)

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [135]:
print(len(study.trials))

50

In [136]:
#Looking at the first trial to see if trails actually have values
print(study.trials[0])

FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.986372710702196], datetime_start=datetime.datetime(2024, 10, 31, 14, 28, 49, 150281), datetime_complete=datetime.datetime(2024, 10, 31, 14, 44, 22, 97967), params={'max_depth': 43, 'learning_rate': 0.5108136365920442, 'reg_lambda': 3.006867379729441}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'max_depth': IntDistribution(high=60, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=1.0, log=False, low=0.01, step=None), 'reg_lambda': FloatDistribution(high=10.0, log=False, low=0.0, step=None)}, trial_id=0, value=None)

In [137]:
vis.plot_optimization_history(study)

In [138]:
vis.plot_slice(study, params=['max_depth', 'learning_rate', 'reg_lambda'])

In [139]:
vis.plot_param_importances(study)

In [140]:
best_trail = study.best_trial

best_params = study.best_params

best_model = xgboost.XGBClassifier(**best_params)

best_model.fit(X_resampled, y_resampled)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.17759220467737735,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=38, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [141]:
# Best F1 score
print(f'Best F12 Score: {best_trail.value}')

Best F12 Score: 0.9872090601508191